# Neale diseases genes (Pascal) and diseases genes (GWAS catalog)

###### First version 17/06/2022
###### Latest modif 18/10/2022

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
import seaborn as sns
from datetime import datetime
import os
import glob

DATE = datetime.now().strftime("%Y-%m-%d")

In [48]:
#save_dir ='/SSD/home/sofia/retina-phenotypes/complementary/GWAS_postprocessing/common_genes_path_snps/'
save_dir ='/NVME/decrypted/scratch/multitrait/UK_BIOBANK_ZERO/genes/'
df_genes_count= pd.read_csv(save_dir +'/genes_count_main_v5.csv')

neale_csv_name='11_10_2022_diseases_genes.csv'
#df_genes_count.head(5)

### - Pre analysis: (example) Show Neale diseases Pascal genes for SBP and DBP:

In [2]:
dir_ = '/NVME/decrypted/scratch/multitrait/UK_BIOBANK_ZERO/gwas/2022_08_03_ventile5/gcorr_diseases/'
file_4079='4079_irnt.gwas.imputed_v3.both_sexes.tsv__gene_scores.p'

df_4079=pd.read_pickle(dir_+file_4079)

file_4080='4080_irnt.gwas.imputed_v3.both_sexes.tsv__gene_scores.p'

df_4080=pd.read_pickle(dir_+file_4080)

In [7]:
str(df_4080)[0:1000]

"[[], [], [['MIR1302-10', 'No SNPs'], ['FAM138A', 'No SNPs'], ['OR4F5', 'No SNPs'], ['RP11-34P13.7', 'No SNPs'], ['RP11-34P13.8', 'No SNPs'], ['AL627309.1', 'No SNPs'], ['RP11-34P13.9', 'No SNPs'], ['AP006222.2', 'No SNPs'], ['RP4-669L17.10', 'No SNPs'], ['OR4F29', 'No SNPs'], ['RP4-669L17.2', 'No SNPs'], ['RP5-857K21.15', 'No SNPs'], ['RP5-857K21.1', 'No SNPs'], ['RP5-857K21.2', 'No SNPs'], ['RP5-857K21.3', 'No SNPs'], ['RP5-857K21.4', 'No SNPs'], ['RP5-857K21.5', 'No SNPs'], ['OR4F16', 'No SNPs'], ['RP11-206L10.3', 'No SNPs'], ['RP11-206L10.5', 'No SNPs'], ['RP11-206L10.2', 'No SNPs'], ['RP11-206L10.9', 'No SNPs'], ['AL669831.1', 'No SNPs'], ['FAM87B', 'No SNPs'], ['LINC00115', 'No SNPs'], ['FAM41C', 'No SNPs'], ['AL645608.2', 'No SNPs'], ['RP11-54O7.16', 'No SNPs'], ['RP11-54O7.1', 'No SNPs'], ['RP11-54O7.2', 'No SNPs'], ['RP11-54O7.3', 'No SNPs'], ['SAMD11', 'No SNPs'], ['AL645608.1', 'No SNPs'], ['NOC2L', 'No SNPs'], ['KLHL17', 'No SNPs'], ['PLEKHN1', 'No SNPs'], ['C1orf170', 'No S"

## 1- Read the Neale Pascal genes for all the diseases

In [50]:
p_value_min = 5.7  # -math.log10(0.05/len(x))

#input_dir='/HDD/data/ukbb/disease_sumstats/files_modified/'
input_dir='/HDD/data/ukbb/disease_sumstats/VARIANTS/'
l_diseases_all=[]

#os.chdir('/HDD/data/ukbb/disease_sumstats/files_modified/')
os.chdir('/HDD/data/ukbb/disease_sumstats/VARIANTS/')
for file in glob.glob("*__gene_scores"):
    #print(file)
    #file='4080_irnt.gwas.imputed_v3.both_sexes.tsv'
    #df = pd.read_csv(input_dir+file+'__gene_scores', delimiter='\t', names =['gen', 'p']) #, index_col=None, header=0)
    df = pd.read_csv(input_dir+file, delimiter='\t', names =['gen', 'p']) #, index_col=None, header=0)

    df['file_col']=file

    df['-log10(p)'] = -np.log10(df['p'])
    y = df[df['-log10(p)'] >= p_value_min]
    df_significant = y.sort_values('-log10(p)', ascending=False)
    pheno, b = file.split(".gwas.imputed_v3.both_sexes.tsv__gene_scores")
    aux, pheno_name = pheno.split("only_rs_notna_mod_variants_")
    
    data={
    'pheno':  pheno,
    'name_pheno': pheno_name,
    'N genes': len(df_significant),
    'names': df_significant['gen'].to_list()
    }
    l_diseases_all.append(data)

df_diseases_all =pd.DataFrame(l_diseases_all)
    
    #print(pheno, ' Significant number of genes: ', len(df_significant))

In [80]:
df_diseases_all

,pheno,name_pheno,N genes,names
0,only_rs_notna_mod_variants_5843_1,5843_1,1,[EXOSC4]
1,only_rs_notna_mod_variants_1717,1717,468,"[CDK10, RP11-368I7.4, DPEP1, CHMP1A, SPATA33, ..."
2,only_rs_notna_mod_variants_4080_irnt,4080_irnt,959,"[NPPA, NPPB, MTHFR, CLCN6, C1orf167, NPR3, AGT..."
3,only_rs_notna_mod_variants_5855_1,5855_1,0,[]
4,only_rs_notna_mod_variants_4056_irnt,4056_irnt,0,[]
5,only_rs_notna_mod_variants_4079_irnt,4079_irnt,910,"[CSK, RP1-278O22.1, LMAN1L, CYP1A2, CPLX3, ULK..."
6,only_rs_notna_mod_variants_4079_raw,4079_raw,905,"[NPPA, NPPB, MTHFR, CLCN6, C1orf167, RP1-278O2..."
7,only_rs_notna_mod_variants_3894_irnt,3894_irnt,0,[]
8,only_rs_notna_mod_variants_5843_3,5843_3,0,[]
9,only_rs_notna_mod_variants_3627_irnt,3627_irnt,0,[]
10,only_rs_notna_mod_variants_102_raw,102_raw,884,"[MYH6, CMTM5, IL25, EFS, KIAA1755, MYH7, SLC22..."
11,only_rs_notna_mod_variants_21021_raw,21021_raw,0,[]
12,only_rs_notna_mod_variants_21021_irnt,21021_irnt,3,"[PALM, TEX41, PRSS57]"
13,only_rs_notna_mod_variants_5855_3,5855_3,0,[]
14,only_rs_notna_mod_variants_5610_2,5610_2,0,[]
15,only_rs_notna_mod_variants_40007_irnt,40007_irnt,0,[]
16,only_rs_notna_mod_variants_4012_irnt,4012_irnt,0,[]
17,only_rs_notna_mod_variants_5832_2,5832_2,0,[]
18,only_rs_notna_mod_variants_1558,1558,276,"[AC109829.1, ADH7, KLB, NPIPB8, SULT1A1, CCDC1..."
19,only_rs_notna_mod_variants_102_irnt,102_irnt,907,"[MYH6, CMTM5, IL25, EFS, KIAA1755, MYH7, SLC22..."
20,only_rs_notna_mod_variants_4080_raw,4080_raw,838,"[NPR3, C11orf89, LSP1, CACNB2, ATP2B1, TNNI2, ..."
21,only_rs_notna_mod_variants_4700_irnt,4700_irnt,0,[]
22,only_rs_notna_mod_variants_4700_raw,4700_raw,0,[]
23,only_rs_notna_mod_variants_2976_irnt,2976_irnt,106,"[HLA-DQB1, XXbac-BPG254F23.7, HLA-DQA1, HLA-DQ..."

In [3]:
df_diseases_all.to_csv('/SSD/home/sofia/retina-phenotypes/complementary/GWAS_postprocessing/'+neale_csv_name, index=False)

## 2- Neale Pascal genes AND GWAS catalog

#### a) Select the diseases of interest on list_pheno_neale

In [9]:
### Read the previous df
df_genes_neale= pd.read_csv('/SSD/home/sofia/retina-phenotypes/complementary/GWAS_postprocessing/'+neale_csv_name, converters={'names': pd.eval})

In [11]:
#df_genes_neale['liststring'] = [''.join(map(str, l)) for l in df_genes_neale['names']]
#df_genes_neale['names'].iloc[4][2]

list_pheno_neale=['4080_irnt'] #list(df_genes_neale['pheno'])
#['4080_irnt', '102_irnt', '4056_irnt', '5610_3', '4079_irnt', '1717', '3894_irnt']

df_genes_neale_red = df_genes_neale[df_genes_neale["name_pheno"].isin(list_pheno_neale)]
#df_genes_neale_red['pheno_name'] = ['SBP_irnt', 'PR_irnt', 'Stroke_irnt', 'Presbyopia_3', 'DBP_irnt', 'Skin_color', 'heart_attack_irnt']
#df_genes_neale_red = df_genes_neale.copy()
#df_genes_neale_red
df_genes_neale_red

,pheno,name_pheno,N genes,names
2,only_rs_notna_mod_variants_4080_irnt,4080_irnt,959,"[NPPA, NPPB, MTHFR, CLCN6, C1orf167, NPR3, AGT..."

In [12]:
### Select the file of interest:
#df_genes_neale_red['names'][df_genes_neale_red['pheno']=='only_rs_notna_mod_variants_4079_irnt']
#set_only_rs_notna_mod_variants_4079_irnt = set(df_genes_neale_red['names'].iloc[5])
#set_only_rs_notna_mod_variants_4079_raw = set(df_genes_neale_red['names'].iloc[6])
#print(len(set_only_rs_notna_mod_variants_4079_irnt), len(set_only_rs_notna_mod_variants_4079_raw))
#print('Intersection of both: ', len(set_only_rs_notna_mod_variants_4079_irnt&set_only_rs_notna_mod_variants_4079_raw))
#df_genes_neale_red.head(2)

#### b) GWAS catalog

In [13]:
dir_catalog = '/HDD/data/GWAS_catalog/'
os.chdir(dir_catalog)

l_genes_shared=[]
for file_name in glob.glob("gwas-association-downloaded_SBP.tsv"): #glob("*.tsv"):
    #print(file_name)
    df_gwas = pd.read_table(dir_catalog+ str(file_name))
    #df_reduced = df_gwas[['MAPPED_TRAIT', 'REPORTED GENE(S)', 'MAPPED_GENE']]
    #print(df_reduced.head(5))
    for i in range(len(df_gwas)):
        gen = df_gwas['REPORTED GENE(S)'].iloc[i]
        for j in range(len(df_genes_neale_red)):
            for m in range(len(df_genes_neale_red['names'].iloc[j])):
                if df_genes_neale_red['names'].iloc[j][m]==gen:
                    data={
                    'Neale_pheno':  df_genes_neale_red['name_pheno'].iloc[j],
                    'MAPPED_TRAIT': df_gwas['MAPPED_TRAIT'].iloc[i],
                    'gene': df_genes_neale_red['names'].iloc[j][m],
                    'gene1': gen,
                    'INITIAL SAMPLE SIZE': df_gwas['INITIAL SAMPLE SIZE'].iloc[i]
                    }
                    l_genes_shared.append(data)

df_genes_shared =pd.DataFrame(l_genes_shared)

In [14]:
### Drop genes duplicated
df_genes_shared_no_dup = df_genes_shared.drop_duplicates(subset = ["gene"])
df_genes_shared_no_dup.reset_index(drop=True)

,Neale_pheno,MAPPED_TRAIT,gene,gene1,INITIAL SAMPLE SIZE
0,4080_irnt,systolic blood pressure,ARNTL,ARNTL,"291,107 British ancestry individuals"
1,4080_irnt,systolic blood pressure,NMT1,NMT1,"291,107 British ancestry individuals"
2,4080_irnt,systolic blood pressure,NR1H3,NR1H3,"291,107 British ancestry individuals"
3,4080_irnt,systolic blood pressure,GIP,GIP,"291,107 British ancestry individuals"
4,4080_irnt,systolic blood pressure,USP36,USP36,"291,107 British ancestry individuals"
...,...,...,...,...,...
200,4080_irnt,systolic blood pressure,RP11-1055B8.6,RP11-1055B8.6,"757,601 European ancestry individuals"
201,4080_irnt,systolic blood pressure,CTNNB1,CTNNB1,"757,601 European ancestry individuals"
202,4080_irnt,systolic blood pressure,POM121C,POM121C,"757,601 European ancestry individuals"
203,4080_irnt,systolic blood pressure,THSD7B,THSD7B,"757,601 European ancestry individuals"
204,4080_irnt,systolic blood pressure,KDM4B,KDM4B,"757,601 European ancestry individuals"

In [15]:
### IMPORTANT. NOT FILTERED BY ETNICITY

In [98]:
#df_genes_shared.to_csv('/SSD/home/sofia/retina-phenotypes/complementary/GWAS_postprocessing/5_09_2022_shared_diseases_genes.csv')

# OLD VERSION (relevant -> create a list with all the genes)

In [37]:
df_diseases=pd.read_csv('/SSD/home/sofia/retina-phenotypes/complementary/GWAS_postprocessing/1_09_2022_diseases_genes.csv')

In [38]:
### Example:
print(len(df_diseases['names'].iloc[4]))
#### Do your strings look like this: “[‘strawberry’, ‘apple’, ‘orange’]”?
# In that case, there is a quick method using the apply() and eval() functions.
df_diseases['names'] = df_diseases['names'].apply(eval)

In [ ]:
## Create a list with all the genes
list_genes_diseases_pascal=[]
for i in range(len(df_diseases)):
    if len(df_diseases['names'].iloc[i])==0: 
        continue
        #print(df_diseases['names'].iloc[i])
    else:
        list_genes_diseases_pascal = list_genes_diseases_pascal + df_diseases['names'].iloc[i]
        #list_genes_diseases_pascal.append(list(df_diseases['names'].iloc[i]))
#list_genes_diseases_pascal

#### N* -> OLD VERSION (does not work)

In [ ]:
##### NEED TO ADD df_genes_count

In [ ]:
for gen in list_genes_diseases_pascal:
    if df_genes_count[df_genes_count['Unnamed: 0']==gen].empty:
        continue
    else:
        print(gen)
        print(df_genes_count[df_genes_count['Unnamed: 0']==gen], '\n')

In [ ]:
##### OLD VERSION

In [ ]:
os.chdir(dir_catalog)

for file_name in glob.glob("*.tsv"):
    #print(file_name)
    df_gwas = pd.read_table(dir_catalog+ str(file_name))
    #df_reduced = df_gwas[['MAPPED_TRAIT', 'REPORTED GENE(S)', 'MAPPED_GENE']]
    #print(df_reduced.head(5))
    for i in range(len(df_gwas)):
        gen = df_gwas['REPORTED GENE(S)'].iloc[i]
        if df_genes_count[df_genes_count['Unnamed: 0']==gen].empty:
            continue
        else:
            print(df_gwas['MAPPED_TRAIT'].iloc[i], df_gwas['INITIAL SAMPLE SIZE'].iloc[i])
            print(df_genes_count[df_genes_count['Unnamed: 0']==gen])
            print('\n')

In [ ]:
#df_genes_count[df_genes_count['Unnamed: 0']=='CTD-2008P7.9']